name: Backend-Workflow
on: 
  push:
    branches: [master]
jobs:
  correr-pruebas:
    name: Correr pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de liberías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        run: python -m unittest discover -s tests -v

  revisar-cubrimiento:
    name: Revisar cubrimiento
    needs: correr-pruebas
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: inzephirum/gha-test-coverage-check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_threshold: '100'
          report_file_path: './coverage/lcov.info'
    