name: Crear Release y mezclar a main
on:
  push:
    branches: [develop]
jobs:
  correr-pruebas:
    name: Correr pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de liberías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        run: python -m unittest discover -s tests -v

  crear-release:
    name: Crear release
    runs-on: ubuntu-latest
    needs: correr-pruebas
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.event.head_commit.message}}
          separator: '-'
      - name: Checkout del repositorio
        if: ${{ steps.split.outputs._0 }} == 'release'
        uses: actions/checkout@v2
      - name: Crear Release
        id: crear_release
        if: ${{ steps.split.outputs._0 }} == 'release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ steps.split.outputs._1 }}
          release_name: Release v${{ steps.split.outputs._1 }}
          body: ${{ steps.split.outputs._2 }}
          draft: false
          prerelease: false
  
  crear-release-mezclar-main:
    name: Crear release y mezclar a main
    runs-on: ubuntu-latest
    needs: correr-pruebas
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.event.head_commit.message}}
          separator: '-'
      - name: Checkout del repositorio
        if: ${{ steps.split.outputs._0 }} == 'main'
        uses: actions/checkout@v2
      - name: Crear Release
        id: crear_release
        if: ${{ steps.split.outputs._0 }} == 'main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ steps.split.outputs._1 }}
          release_name: Release v${{ steps.split.outputs._1 }}
          body: ${{ steps.split.outputs._2 }}
          draft: false
          prerelease: false
      - name: Mezclar a main
        if: ${{ steps.split.outputs._0 }} == 'main'
        run: |
          git fetch && git checkout main
          git merge develop
          git push origin main
