name: Crear Release y mezclar a main
on:
  push:
    branches: [develop]
jobs:
  correr-pruebas:
    name: Correr pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de liberías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        run: python -m unittest discover -s tests -v

  crear-release:
    name: Crear release
    runs-on: ubuntu-latest
    needs: correr-pruebas
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.event.head_commit.message}}
          separator: '-'
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Crear release
        run: |
          git fetch && git checkout develop
          git checkout -b release/v${{ steps.split.outputs._1 }}
          git push -f -u origin release/v${{ steps.split.outputs._1 }}
          git tag v${{ steps.split.outputs._1 }}
          git push --tags
  
  crear-release-mezclar-main:
    name: Crear release y mezclar a main
    runs-on: ubuntu-latest
    needs: correr-pruebas
    if: ${{ contains(github.event.head_commit.message, 'main') }}
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.event.head_commit.message}}
          separator: '-'
      - name: Crear release
        run: |
          git fetch && git checkout develop
          git checkout -b release/v${{ steps.split.outputs._1 }}
          git push -f -u origin release/v${{ steps.split.outputs._1 }}
          git tag v${{ steps.split.outputs._1 }}
          git push --tags
          git fetch && git checkout main
          git merge release/v${{ steps.split.outputs._1 }}
          git push origin main
