name: Backend-Workflow
on: 
  pull_request_review:
    types: [submitted]
jobs:
  correr-pruebas:
    name: Correr pruebas
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de liberías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        run: python -m unittest discover -s tests -v
      - name: Algo
        run: echo ${{github.event.review.state}}
