name: Workflow Auto Perfecto
on:
  push:
    branches:
      - 'feature**'
jobs:
  correr-pruebas:
    name: Correr pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de liberías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        run: python -m unittest discover -s tests -v

  mezclar-a-develop:
    name: Mezclar a develop
    runs-on: ubuntu-latest
    needs: correr-pruebas
    if: ${{ contains(github.event.head_commit.message, 'develop') }}
    steps:
      - name: Mezclar a develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop

  mezclar-a-develop-crear-release:
    name: Mezclar a develop y crear release
    runs-on: ubuntu-latest
    needs: correr-pruebas
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Mezclar a develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
      - name: Crear release
        run: |
          git checkout develop
          git checkout -b release/${{ github.run_id }}
          git push -f -u origin release/${{ github.run_id }}
      - name: Mezclar con rama main
        run: |
          git checkout main
          git merge develop
          git push origin main